import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Header from './components/Header'
import Container from './components/Container'
import NextAuthProvider from './components/NextAuthProvider'
import { ToastifyProvider } from './components/ToastifyProvider'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Capsule | Home',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  login,
  register,
}: {
  children: React.ReactNode
  login: React.ReactNode
  register: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <ToastifyProvider>
          <NextAuthProvider>
            {login}
            {register}
            <Header />
            <Container>{children}</Container>
          </NextAuthProvider>
        </ToastifyProvider>
      </body>
    </html>
  )
}
